services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "n8n start"
    envVars:
      - key: N8N_HOST
        value: n8n.onrender.com # Replace with your actual Render URL *after* deployment
      - key: N8N_PORT
        value: 80
      - key: N8N_PROTOCOL
        value: https
      - key: GENERIC_TIMEZONE
        value: UTC
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
